// Generated by Selenium IDE
import helpers.ApplicationManager;
import model.AccountData;
import model.CollectionData;
import model.CommentData;
import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

public class TestFic extends TestBase{

  @Test
  public void testCollection() {
    ApplicationManager app = new ApplicationManager();
    app.getNavigation().OpenHomePage();
    AccountData user = new AccountData("ars11", "Arif2012");
    app.getAuth().Login(user);
    app.getNavigation().OpenCollections();
    CollectionData collectionData = new CollectionData("мой", "мой личный сборник");
    app.getCollection().CreateNewCollection(collectionData);
  }

  @Test
  public void testComment() {
    ApplicationManager app = new ApplicationManager();
    app.getNavigation().OpenHomePage();
    AccountData user = new AccountData("ars11", "Arif2012");
    app.getAuth().Login(user);
    app.getNavigation().OpenBlog();
    CommentData commentData = new CommentData("комментарий");
    app.getComment().CreateComment(commentData);
  }

}
